# Site settings
title: Francis Rosinante
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Francis Rosinante 
user_description: curious, enthusiastic, and adventurous
user_title: programmer
email: francis.rosinante@gmail.com
twitter_username: itsfranrose 
# instagram_username:  
# facebook_username: mauricio.urraco
# linkedin_username: murraco
github_username: itsfranrose 
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum
footer_text: All people are different people.

exclude: ['package.json', 'src', 'node_modules', 'vendor']

